name: "build-test"

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: |
          npm ci
          npm test
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Create maven settings.xml
        uses: ./
        with:
          servers: '[{"id": "foo", "username": "fu", "password": "bar" }]'
          mirrors: '[{ "id": "nexus", "mirrorOf": "!my-org-snapshots,*", "url": "http://redacted/nexus/content/groups/public" }]'
          repositories: '[{"id": "foo", "url": "https://fu.bar"}]'
          plugin_repositories: '[{"id": "foo-plugin", "url": "https://fu.bar.plugin"}]'
          profiles: '[{ "id": "foo.profile", "name": "foo.profile", "url": "http://foo.bar.profile", "properties": { "foo": "property-1", "bar": "property-2"} }]'
      - run: |
          cat ~/.m2/settings.xml

